### ISSUE TITLE
[Task] 마이페이지 개발

### ISSUE THREAD

**Issue by kongyb** [codestates/CloudLounge#10]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 마이페이지 개발

### TODO
1. [ ] 최초 렌더링시 서버에 유저의 정보를 요청 (GET /user/info)
2. [ ] 회원정보 수정 버튼 클릭시 회원정보 수정 페이지로 이동
3. [ ] 회원탈퇴 버튼 클릭시 확인하는 Modal ...?
