### ISSUE TITLE
[Task] 관리자페이지 개발

### ISSUE THREAD

**Issue by kongyb** [codestates/CloudLounge#13]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 관리자페이지 개발

### TODO
1. [ ] 최초 렌더링시 서버에 신고횟수 10회 이상인 라운지정보 요청 (GET /admin)
2. [ ] 하나의 라운지를 표현할 수 있는 컴포넌트를 재사용(라운지의 이름, 신고횟수, 삭제버튼)
3. [ ] 삭제버튼을 클릭시 서버에 신고내역을 삭제하는 요청(DELETE /admin/:loungeId)
