### ISSUE TITLE
[Task] 회원정보 조회, 로그아웃 api 구현

### ISSUE THREAD

**Issue by KRLEESEUNGJAE** [codestates/CloudLounge#17]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 회원정보 조회, 로그아웃 api 구현

### TODO
1. [x] 회원정보 조회 controller 작성
2. [x] 로그아웃 controller 작성
3. [x] postman을 통한 테스트 진행 

### `3h`
