### ISSUE TITLE
[Task] 라운지 정보 조회 api 구현

### ISSUE THREAD

**Issue by KRLEESEUNGJAE** [codestates/CloudLounge#22]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 라운지 정보 조회 api 구현

### TODO
1. [x] DB에서 정보를 잘 가져오는지 점검 
2. [x] 정보조회 controller 작성 
3. [x] postman을 통한 테스트 진행 

### `3h`
