### ISSUE TITLE
[Task] 라운지 신고 api 구현 

### ISSUE THREAD

**Issue by KRLEESEUNGJAE** [codestates/CloudLounge#23]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 라운지 신고 api 구현 

### TODO
1. [x] 라운지 신고 정보를 db에 input 테스트 
2. [x] 신고 controller 작성 
3. [x] postman을 통한 테스트 진행 

### `3h`
