### ISSUE TITLE
[Task] 라운지 위치정보 api 구현

### ISSUE THREAD

**Issue by KRLEESEUNGJAE** [codestates/CloudLounge#24]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 라운지 위치정보 api 구현

### TODO
1. [x] 라운지 주소를 DB에서 가져오는 query 테스트 
2. [x] 위치정보 controller 작성
3. [x] postman을 통한 테스트 진행 

### `3h`
