### ISSUE TITLE
[Task] 관리자 페이지 신고정보 조회 api 구현 

### ISSUE THREAD

**Issue by KRLEESEUNGJAE** [codestates/CloudLounge#25]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 관리자 페이지 신고정보 조회 api 구현 

### TODO
1. [x] 신고 개수 20개 이상인 라운지의 정보를 가져오는 query 테스트 
2. [x] 관리자 페이지 controller 작성
3. [x] postman을 통한 테스트 진행 

### `3h`
