### ISSUE TITLE
[Task] 관리자 페이지 신고 처리 후 삭제 api 구현 

### ISSUE THREAD

**Issue by KRLEESEUNGJAE** [codestates/CloudLounge#26]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 관리자 페이지 신고 처리 후 삭제 api 구현 

### TODO
1. [x] 관리자가 신고된 라운지의 처리를 완료한 후 삭제할 수 있더록 쿼리 작성 
ex) 해당 라운지의 아이디에 해당하는 신고 정보를 삭제  
2. [x] 관리자 페이지  controller 작성
3. [x] postman을 통한 테스트 진행 

### `3h`
