### ISSUE TITLE
[Task] 첫화면 페이지 개발

### ISSUE THREAD

**Issue by kongyb** [codestates/CloudLounge#4]
### ISSUE
- Group:  `client`
- Type:  `feature`
- Detail: 첫화면 페이지 개발

### TODO
1. [ ] kakao Map API연동후 화면에 지도 그리기
2. [ ] 서버에 요청을 보내 흡연장 정보를 얻고 지도상에 마커 생성 (GET /lounge)
3. [ ] 마커 클릭시 모달(흡연장정보) 생성
