### ISSUE TITLE
[Task] 자세히보기 페이지 개발

### ISSUE THREAD

**Issue by kongyb** [codestates/CloudLounge#6]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 자세히보기 페이지 개발

### TODO
1. [ ] 댓글 하나를 표현할 수 있는 컴포넌트를 만들고 재사용
2. [ ] 댓글이 없을 경우...?
3. [ ] 비로그인 상태에서 댓글 작성 클릭시 로그인 페이지로 이동
