### ISSUE TITLE
[Task] 댓글작성 페이지 개발

### ISSUE THREAD

**Issue by kongyb** [codestates/CloudLounge#7]
### ISSUE
- Group:  `client`
- Type:  `feature`
- Detail: 댓글작성 페이지 개발

### TODO
1. [ ] 별점을 선택할 수 있는 컴포넌트
2. [ ] 댓글의 길이를 검사(255자 이하)
3. [ ] 제출하기 버튼 클릭시 서버에 댓글 등록 요청 (POST /lounge/comment)
