### ISSUE TITLE
[Task] 회원가입 페이지 개발

### ISSUE THREAD

**Issue by kongyb** [codestates/CloudLounge#9]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 회원가입 페이지 개발

### TODO
1. [ ] 이메일과 패스워드 작성부분의 유효성 검사
2. [ ] 패스워드와 패스워드 확인 동일한지 검사
3. [ ] 제출버튼 클릭시 서버에 회원가입 요청 (POST /user/signup)
4. [ ] 회원가입 성공시 로그인 페이지 이동 ...?
